### ISSUE TITLE
Non-ASCII characters in ".list" files

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#13]
Email note from @jteresco:

> Since .list files should contain only ASCII characters, my program crashes when it encounters these.  I am sure I can fix this some time, but for now, please be careful not to have any non-ASCII characters in .list files.

I had umlauts in my list file which were commented (#) though.

**Comment by jteresco** [comment]
Since none of the items that belong in .list files contain any non-ASCII characters, I'd like to keep the rule that no non-ASCII files should be submitted as .list files.  At the moment, there are a handful of UTF-8 list files (which seem not to cause trouble, as long as no special characters are used) but all others are ASCII, some with, some without CRLF delimiters.

**Comment by jteresco** [comment]
Closing this issue.  We'll maintain the rule that all .list and .wpt files should be in plain ASCII text.
