### ISSUE TITLE
DUPLICATE_COORDS check

### ISSUE THREAD

**Issue by rickmastfan67** [TravelMapping/DataProcessing#2]
Shouldn't this check mention what waypoints are duplicated?

For example:
fl.i295		DUPLICATE_COORDS	(30.166494,-81.55508)	fl.i295;;;;DUPLICATE_COORDS;(30.166494,-81.55508)

How could I tell what 'points' have the duplicated coordinates with ease?  This check should mention the points effected just like the old datacheck did.

**Comment by yakra** [comment]
The problem is that the CSV only has three columns for labels, and more than three points can potentially have the same coords. (This often happens on multiplexes after I run a route thru GISplunge.) My solution is just to inspect the route in WPTedit and suss it out from there.

**Comment by jteresco** [comment]
I will probably have to check this weekend, but I think I can address by putting every pair of problematic coordinates.  So if A, B, and C, all have the same coordinates, there would be entries listing A and B, A and C, and B and C.  If there was a fourth point, D, we would have AB, AC, AD, BC, BD, and CD.

Are there situations where a single route legitimately has more than 2 labels at the same coords (I mean, FP situations)?  Are the current FPs anything other than loops and routes that otherwise intersect themselves?

**Comment by rickmastfan67** [comment]
PA US-19 Truck has duplicated coordinates and isn't a loop because of limited space for an interchange on I-376 (Parkway West) right outside of the Fort Pitt Tunnel.

**Comment by yakra** [comment]
Jim: sounds OK. I'm agnostic re how it should be displayed in the datacheck tables, but I would like to see the existing FP syntax used:
* so the ones we've already flagged will stay flagged
* to kill multiple birds with one stone, if datacheck will output multiple lines, one for each point pair

**Comment by jteresco** [comment]
To @yakra's point about flagging ones we already flagged, I think this is something I can address.  Let's not spend much effort on FP flagging until I can take a look and see if I can get at least a significant chunk of the 4300+  FPs from CHM marked automatically in TravelMapping.

**Comment by jteresco** [comment]
Resolved, I believe.  I did nothing specific to account for a situation with 3 duplicated coordinate points, but I expect they'd be flagged in pairs the way I mentioned earlier in the discussion if any are ever introduced.
