### ISSUE TITLE
Output log for unused altRouteNames

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#230]
We already have _unusedaltlabels.log_ but an _unusedaltroutenames.log_ would help to eliminate leftover.

**Comment by yakra** [comment]
First create an `unused_alt_route_names` set for each `Route`, much like the existing `unused_alt_labels`. Populate it during `Route` construction, when the `alt_route_names` list is created. Then, either:
* During .list processing, every time a Region+Name combo is matched, remove it from the `unused_alt_route_names` set. For primary names, we're just removing something that's already not there. :) This is the simpler-to-code option.
* Create *two* `route_hash` tables, one for primary names and one for AltRouteNames. When a lookup in the primary table fails, check the alt table. When an AltRouteName match is found, remove it from the set.
  - Faster where, for the 99.82% of good .list lines not using AltRouteNames, we're not searching for a nonexistent primary name in the `unused_alt_route_names` set.
  - A tiny bit slower in the 0.18% of cases where AltRouteNames are involved, because we're looking up these entries in *two* hash tables instead of one, and in `Unknown region/highway combo` cases (which number 3.6x as many).
  Counterbalanced to whatever degree by the primary name lookups being a *tiny* bit faster due to using a smaller set.
  - For another potential speedup, this enables us to remove the existing `alt_route_names` list (which would also save some RAM).
    - Right now, every time we find a region/highway match, we iterate through the `alt_route_names` list until a match is found, to add the `deprecated route name ... -> canonical name` note to the user log.
    - No iterating; instead, just add the note to the log as soon as a match is found via the `alt_route_hash` table.

**Comment by yakra** [comment]
I think it would be useful to have list of both unused and in-use AltLabels.

**Comment by yakra** [comment]
**C++ Progress:**
* No diffs in stats .csv files.
* User log diffs all make sense. All of them are the same basic idea as:
  ```diff
  dave1693.log:
  2d1
  < Waypoint label(s) not found in line: RI US1AltPro I-195(2) I-195(6)
  6c5
  < Processed 2577 good lines marking 27712 segments traveled.
  ---
  > Processed 2578 good lines marking 27712 segments traveled.
  ```
  `I-195(2)` and `I-195(6)` refer to the same waypoint due to the sequential -> mileage-based renumbering.
  * If we want, we can add a note to the .log file such as
    `Equivalent waypoint labels mark zero distance traveled in line: RI US1AltPro I-195(2) I-195(6)`
    and not count the line toward the total number of good lines.
* No diffs in nmp_merged .wpt files.
* No diffs in post-processed graphs.
* No diffs in main .log files, except...
* Old & new **pointsinuse.log** and **unusedaltlabels.log** differ.
  In a way that does not affect anybody's stats.
  The how-and-why should be pretty understandable; I'm only starting the process of understanding it.

**Comment by yakra** [comment]
We're down to four labels that have left unusedaltlabels.log and entered pointsinuse.log:
* `VA US50 I-66(76)`
* `NC US17BusWlm MilCut`
* `RI RI1APro I-195(6)`
* `WI WI136 WI159`

All of these were used in .list lines paired with the same waypoint's primary label:
* `VA US50 I-66(76) VA/DC`
* `NC US17BusWlm MilCut US17_N`
* `RI US1AltPro I-195(2) I-195(6)`
* `WI WI123 CRDL WI159`

They correspond to `Waypoint label(s) not found in line:` errors as in the example in my last post; the AltLabels never got checked for usage:

```py
for w in r.point_list:                                             #
    upper_label = w.label.lstrip("+*").upper()                     #
    if list_label_1 == upper_label or list_label_2 == upper_label: # Primary label matches either list_label_1 or list_label_2,
        point_indices.append(checking_index)                       # and IF block executes.
        r.labels_in_use.add(upper_label)                           #
    else:                                                          # Thus this never happens.
        for alt in w.alt_labels:                                   #
            if list_label_1 == alt or list_label_2 == alt:         #
                point_indices.append(checking_index)               #
                r.labels_in_use.add(alt)                           #
                r.unused_alt_labels.discard(alt)                   #
```

These labels are unused in the sense that they don't result in any clinched mileage for anybody. Removing them from the .wpt files would not harm anyone's stats. Thus I like the idea of doing as the existing code does, and counting them as unused. We can cut out the cruft, allow them to expire and re-enter the stream. :)

>  * If we want, we can add a note to the .log file such as
    `Equivalent waypoint labels mark zero distance traveled in line: RI US1AltPro I-195(2) I-195(6)`
    and not count the line toward the total number of good lines.

* This would provide a little forewarning if a user checks their .log before we get around to removing the label and slapping them with a `Waypoint label(s) not found in line` error.
* It's a cheap thing to do (in the rare cases it happens) while getting these AltLabels to remain flagged unused and slimming down the code.
* In the immediate term during development, it yields the most sane user log diffs.

**Comment by yakra** [comment]
> I think it would be useful to have lists of both unused and in-use AltRouteNames.

In-use AltRouteNames is a bit questionable. More useful would be a .log of all in-use .list names, whether primary or alternate.

**Comment by yakra** [comment]
Similar to ["option 2" for waypoint labels](http://forum.travelmapping.net/index.php?topic=3613), .list names will be flagged as in-use:
* only if the entire.list line, both waypoint labels included, is valid and credits a traveler with non-zero distance traveled.
* a valid region/route combo alone is not sufficient.

**Comment by yakra** [comment]
**Squashed commits on BiggaTomato**
in case I ever want to refer back to them individually...

1. `265c35d13a6a14e66da1d6cee134a3a31c038427` (#308)
   strip .list comments before counting fields
2. `1a2932ad6db82301d5c3d061c7d7772aebc112cb` (#58)
   C++: refactor chopped route (4-field) list line parsing into its own file
3. `f6f72bfa3c9eb08cde28323e7f9b8af2a31e7d8b` (#278, #325)
   label hashes & DUPLICATE_LABELS datacheck
4. `89cffb2dacf80d863e4b6c1a8fd2a122cfa96adb` (#278)
   Py comment cleanup before hash-based .list proc
5. `c9028d6f2ea77bdc06eb9c48e6446ce09fa7087c` (#278, #326)
   hash-based .list processing
6. `c705341ef8425ab5febb8f3f3fca6a7f2ea2e415` (#274)
   C++: eliminate strtok_mtx
7. `0ce95bf2f7d7db138cb37b1494e65fd25f3f8f9b` (#230)
   refactor pointsinuse.log & unusedaltlabels.log
   to be written in the same loops.
8. `9043605efd6b2197aaa42cfe561142ac1170ec8b` (#278)
   more precise label_hash comments
9. `d76378549eae291dd3b79c5c2c28c30fa21561a9` (#230)
   separate pri_list_hash & alt_list_hash
10. `34640f71e9567fd7813ef8ab3e90db5b80a413f9` (#230)
    listnamesinuse.log & unusedaltroutenames.log
11. `512988888016b945589a9428752ee4e08b2dbd52` (https://github.com/TravelMapping/DataProcessing/issues/58#issuecomment-629957813)
    Route::store_traveled_segments
12. `f904d4bf406af54ac600cdea06feb0acab7ae99e` (#275)
    user log warning for DUPLICATE_LABELs
13. `25a33ce0b019dfdae943caae6358369fc1f86418` (https://github.com/TravelMapping/DataProcessing/issues/326#issuecomment-631662636)
    control chars -> '?' in log error msg labels
