### ISSUE TITLE
Unexpected LABEL_SELFREF error

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#28]
I get 2 LABEL_SELFREF errors I don't understand:

`deu.b065ast;B61/B65;;;LABEL_SELFREF;
deu.b082ast;B6/B82;;;LABEL_SELFREF;`

It's my AST thing. AST is entered as banner in deub csv files.

`deub;DEU;B65;AST;;Minden;deu.b065ast;`
`deub;DEU;B82;AST;;Goslar;deu.b082ast;`

I've checked the respective lines and they seem to be correct compared to other AST routes which don't have LABEL_SELFREF errors, e.g.:

`deub;DEU;B8;AST;;Köln-Mülheim;deu.b008ast;`
`deub;DEU;B22;AST;;Bamberg;deu.b022ast;`

In addition, B82 has two SELFREFs but only one is detected!

I think the error is detected if 2 route names are used, B61/B65 and B6/B82 are detected but B82, B8 or B22 are not detected!

I don't know what's wrong, that the 2 errors are detected or that all other errors are not detected?
Well, it's not a big deal, I could just add them to datacheckfps.csv but it's a bug and I don't know if there are any subsequent errors because of this bug....

**Comment by jteresco** [comment]
Looking back at old issues looking for items that need some attention.  Is this still an accurate description of the situation?

**Comment by michihdeu** [comment]
yes.

**Comment by yakra** [comment]
Looks like with the German split, these routes are now
https://travelmapping.net/hb/showroute.php?r=deunw.b065min
https://travelmapping.net/hb/showroute.php?r=deuni.b082gos
with datacheckfps.log entries:
```
deuni.b082gos;B6/B82;;;LABEL_SELFREF;
deuni.b082gos;B82_W;;;LABEL_SELFREF;
deunw.b065min;B61/B65;;;LABEL_SELFREF;
```
Correct?
*(They're not AST anymore?)*

**Pending LABEL_SELFREF changes:**
* will avoid flagging these, because the points are colocated with same-designation routes.
* If they *were* still AST, they'd not be flagged due to a [banner-matching requirement](https://forum.travelmapping.net/index.php?topic=62.msg25901#msg25901).

**Comment by michihdeu** [comment]
yep, I've replaced the AST banners by abbrevs
