### ISSUE TITLE
E55/E843/A14/A14Bar@+X01

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#32]
There's a data check error indicating that E55/E843/A14/A14Bar@+X01 has a hidden junction but there are already [two unprocessed FPs](http://tm.teresco.org/logs/unmatchedfps.log)...

**Comment by michihdeu** [comment]
Dunno why it happened and what has been changed but it's OK now...

**Comment by michihdeu** [comment]
The error is back with the latest update. I'm 100% sure that it was fine before!

**Comment by rickmastfan67** [comment]
Alerting @terescoj @jteresco so he's fully aware of this.

**Comment by jteresco** [comment]
This one doesn't seem to be causing a problem now.  Can we close?

**Comment by michihdeu** [comment]
I think there is not problem (or we have not yet detected it) but the issue still persists. Anything wents wrong in the code and should be checked one day. Low priority though.

**Comment by yakra** [comment]
http://forum.travelmapping.net/index.php?topic=2073

**Comment by yakra** [comment]
All of the HIDDEN_JUNCTION entries in datacheckfps.csv are showing up in unmatchedfps.log.
```
fra.e15;E15/A9/E80/A709@+A709_W;;;HIDDEN_JUNCTION;4
fra.e15;E15/A9/E80/A709@+A709_W;;;HIDDEN_JUNCTION;4
fra.e15;E15/A9/A709/E80@+A709_W;;;HIDDEN_JUNCTION;4
fra.e15;E15/A9/A709/E80@+A709_W;;;HIDDEN_JUNCTION;4
fra.e15;E15/A9/A709/E80@+A709_W;;;HIDDEN_JUNCTION;4
ita.e55;E55/E843/A14/A14Bar@+X01;;;HIDDEN_JUNCTION;4
nor.rv658;Rv658@+X456802;;;HIDDEN_JUNCTION;4
nor.rv658;Rv658@+X456802;;;HIDDEN_JUNCTION;4
nor.rv658;Rv658@+X456802;;;HIDDEN_JUNCTION;4
nor.rv658;Rv658@+X456802;;;HIDDEN_JUNCTION;4
```

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/blob/5b718fedfb6c42fc3bb1102dcb91a28330fe095e/siteupdate/python-teresco/siteupdate.py#L1571
happens as part of
https://github.com/TravelMapping/DataProcessing/blob/5b718fedfb6c42fc3bb1102dcb91a28330fe095e/siteupdate/python-teresco/siteupdate.py#L1422-L1435
The HighwayGraph is initialized on line 3047:
https://github.com/TravelMapping/DataProcessing/blob/5b718fedfb6c42fc3bb1102dcb91a28330fe095e/siteupdate/python-teresco/siteupdate.py#L3041-L3047
Making datacheck false positives occurs in lines **2472-2493** -- *before* the HighwayGraph is initialized, and thus before the HIDDEN_JUNCTION entries are appended to datacheckerrors.

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/issues/32#issuecomment-255668463
> Dunno why it happened and what has been changed but it's OK now...

My suspicion is that around that time Jim ran a site update with either the "-k" or "--skipgraphs" switch.

**Comment by jteresco** [comment]
The root of the problem here is that we have a group of datacheck errors that are only going to be detected when graph generation happens.  Maybe the answer is that the master graph needs to be generated every time to allow these datachecks to occur, but only generate all of the subgraphs (the time consuming part) when there's no -k flag.  Then move the FP/unmarked FP stuff to after that graph is generated.

**Comment by michihdeu** [comment]
Yes, it would be great to generate the master graph with every update. I don't like that errors appear and disappear without knowing the reason.

**Comment by yakra** [comment]
The solution of generating just the master graph every time makes sense, I can look into this later on.

However: HIDDEN_JUNCTION suffers from the same problem as VISIBLE_HIDDEN_COLOC, due to indeterminate point ordering in the QuadTree.
When I run the modified siteupdate.py (move lines 2246-2517 to just before line 3223) on my machine (with most systems commented out to speed the process up), I get
`fra.a009;A9/A709/E15/E80@+A709_W;;;HIDDEN_JUNCTION;4`
Running the canonical siteupdate.py with all systems, I get
`fra.e15;E15/E80/A9/A709@+A709_W;;;HIDDEN_JUNCTION;4`
Meanwhile, on-site, we have
`fra.e15;E15/A9/A709/E80@+A709_W;;;HIDDEN_JUNCTION;4`

Just changing the data in the Waypoints fields (say, to the label on the route in question, `+A709_W` in this case) is not sufficient, as the datacheck error itself can change. Note the `fra.a009` vs `fra.e15`.

**Comment by yakra** [comment]
@si404, I've updated the HIDDEN_JUNCTION FP entries:
https://github.com/yakra/HighwayData/commit/ab5301fb10eda1f74d00a5b5399d1166637cf31d

**Comment by michihdeu** [comment]
It works! Thanks @yakra 👍
