### ISSUE TITLE
datacheck.sh: AttributeError: 'ConnectedRoute' object has no attribute 'mileage'

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#394]
I forgot to remove the abbrev. column for two lines when copying the lines from csv to _con.csv file: https://github.com/TravelMapping/HighwayData/pull/4455/commits/c97f37a45f298b693aade19e902f5860d9298af1

The datacheck.sh output was:

```
[164.8] Writing highway data stats log file (highwaydatastats.log).
Traceback (most recent call last):
  File "./siteupdate.py", line 3376, in <module>
    hdstatsfile.write(cr.readable_name() + ": " + "{0:.2f}".format(cr.mileage) + " mi")
AttributeError: 'ConnectedRoute' object has no attribute 'mileage'
Sat Jan  2 15:45:33 EST 2021
datacheck.sh: complete
```

I got NO additional info above (where the system is processed) and had to look up the whole csv file in a spreadsheet application.

________________

I had a similar error in the past but got more detailed info above (I think it was something like "no connected route found for xxx" and could check the line before and found the error).
https://github.com/TravelMapping/HighwayData/pull/4431/commits/fbf64b2a8afa632cf9d2358e6d30ffd12c7aaef3 + https://github.com/TravelMapping/HighwayData/pull/4410/commits/8c1672be3c50400dcf87716887511bc2da3b0da2

________________

1. Why does the error text refer to a 'mileage' attribute? There is nothing like that in the csv files. Can we output a better error message?
2. Why was there no additional detailed info today - but 6 and 14 days ago?
3. Is it possible to output the additional detailed info - if there is one - at the end before the data verification is aborted?

**Comment by yakra** [comment]
1. This error message isn't one we intentionally designed to output. It's is not from **siteupdate.py** itself, but rather **python3**, which barfs upon trying to access an attribute of the variable that does not exist. (Due to the nature of C++ and Python's different type systems, this error *can not exist* in the C++ version). IOW, there's a bug somewhere.

2. > I had a similar error in the past but got more detailed info above (I think it was something like "no connected route found for xxx" and could check the line before and found the error).
TravelMapping/HighwayData@fbf64b2 + TravelMapping/HighwayData@8c1672b

    This deals with ConnectedRoute CSVs, but is an unrelated error. Then, siteupdate itself reported an invalid number of fields in a CSV line:
https://github.com/TravelMapping/DataProcessing/blob/362587e953b4d48e7ed3466b6d355f3834a3bcfc/siteupdate/python-teresco/siteupdate.py#L1124-L1125
Now, siteupdate expects an attribute to be attached to a specific variable that isn't.

3. Right now no, since siteupdate.py crashes before we can get that far. Other than that, I can't give a meaningful yes/no answer. Once the underlying bug is fixed, there will hopefully no longer be anything *to* output at that point.

Whatever's going on, it's [probably my bad](https://github.com/TravelMapping/DataProcessing/blame/362587e953b4d48e7ed3466b6d355f3834a3bcfc/siteupdate/python-teresco/siteupdate.py#L3375-L3376).

@michihdeu, were you running datacheck.sh on noreaster, or a different system?

**Comment by michihdeu** [comment]
noreaster

**Comment by yakra** [comment]
@michihdeu wrote:
> TravelMapping/HighwayData@fbf64b2 + TravelMapping/HighwayData@8c1672b

Thanks for this info. I was able to load up the parent commit for each and reproduce the problem on lab1.

> I had a similar error in the past but got more detailed info above (I think it was something like "no connected route found for xxx" and could check the line before and found the error).

I see `ERROR: Could not parse frabfcd71_con.csv line: [frabfcd71;D182;-71;;Dulphey;frabfc.d018271], expected 5 fields, found 6` (TravelMapping/HighwayData@90b185fc21c6c5884a6d2f0788c8aafb03ebb8b9) inline in siteupdate.log. As noted, we don't make it to the point of aborting due to `ErrorList` errors & seeing it again.

**Comment by yakra** [comment]
> I had a similar error in the past but got more detailed info above (I think it was something like "no connected route found for xxx" and could check the line before and found the error).

Sounds like a bit of a different underlying error in that case, that played out differently.

When I run the C++ siteupdate with TravelMapping/HighwayData@90b185f, I do see
```
ERROR: frabfcd71.csv: root frabfc.d018271cyr not matched by any connected route root.
ERROR: frabfcd71.csv: root frabfc.d018271 not matched by any connected route root.
```
and then eventually
```
[45.1] ABORTING due to 4 errors:
1: Could not parse frabfcd71_con.csv line: [frabfcd71;D182;-71;Cyr;Saint-Cyr;frabfc.d018271cyr], expected 5 fields, found 6
2: Could not parse frabfcd71_con.csv line: [frabfcd71;D182;-71;;Dulphey;frabfc.d018271], expected 5 fields, found 6
3: frabfcd71.csv: root frabfc.d018271cyr not matched by any connected route root.
4: frabfcd71.csv: root frabfc.d018271 not matched by any connected route root.
```

So I know that:
* C++ version does not construct the `ConnectedRoute` object and link it to a `Route`. Good!
* Python version does. Bad!

This is where to start looking for answers.

**Comment by yakra** [comment]
I think I've fixed it. Testing.
