### ISSUE TITLE
Optimize data check output

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#574]
- [Remove "skip lines"](https://forum.travelmapping.net/index.php?topic=5359.msg30338#msg30338)
`./datacheck.sh: SKIPPING nmpbyregion (no ../nmpfilter/nmpbyregion executable)`
`./datacheck.sh: SKIPPING file copies and DB update`
- [Highlight success message by blank lines](https://forum.travelmapping.net/index.php?topic=5359.msg30334#msg30334)
- [Nix or massivly reduce progress dots](https://forum.travelmapping.net/index.php?topic=5359.msg30350#msg30350)

**Comment by yakra** [comment]
> [Nix or massivly reduce progress dots](https://forum.travelmapping.net/index.php?topic=5359.msg30350#msg30350)

I wrote on the forum:
> I've thought about nixing all the dots for each Route when *Reading waypoints for all routes.*
It'd be nice to not have to whack Page Down 11 times to get past that stuff when siteupdate.log is loaded into `less`.

In a similar vein...
* This would make the output for *Reading waypoints for all routes* look a lot like that of *Reading systems list*.
WRT *Reading systems list*, on the one hand, using progress dots instead of the full `systemname` would slim it down and take less space onscreen.
On second thought though, I'd like to keep this as-is. If something causes a crash at this stage of the program, all I have to do is run `siteupdateST` or `siteupdate -t 1`, and the last system listed is where I need to start looking for problems.
* *Writing near-miss point merged wpt files* has a similar appearance, and is a candidate for slimming down to progress dots. These routines are pretty stable, haven't had any substantial changes in a long time, and probably won't for the foreseeable future, so no need to worry about any specific system causing a crash.
Low priority though:
  * `nmp_merged` files aren't done in `siteupdate --errorcheck` (aka `datacheck`).
  * @jteresco [has](https://github.com/TravelMapping/DataProcessing/issues/565) [proposed](https://forum.travelmapping.net/index.php?topic=5363) removing them from production site updates.
* [ ] Slim down *Processing traveler list files* a bit by only printing the `traveler_name` and omitting the `.list` extension.

**Comment by michihdeu** [comment]
Talking about reading systems.... Do we need the "ignored systems" output?

It's a long list right now..... Ok, Texas is your bad and France my bad but.... do we need it?

@denishanson the five commented jpnh entries are superfluous now, aren't they?

`Ignored comment in systems.csv: #Preview Systems
Ignored comment in systems.csv: #eure2;EUR;UNECE 'E' Roads (Srpska renumbering / Italy split);TMgreen;3;preview
Ignored comment in systems.csv: #eursf2;EUR;Europe Select Named Freeways (Italy split);TMteal;2;preview
Ignored comment in systems.csv: #itaa2;ITA;Italy Autostrada (Italy split);TMblue;1;preview
Ignored comment in systems.csv: #itass2;ITA;Italy Strade Statali (Italy split);TMlightsalmon;4;preview
Ignored comment in systems.csv: #jpnhhk;JPN;Japan Ippan Kokudō - Hokkaidō;TMlightsalmon;4;preview
Ignored comment in systems.csv: #jpnhks;JPN;Japan Ippan Kokudō - Kansai;TMlightsalmon;4;preview
Ignored comment in systems.csv: #jpnhkt;JPN;Japan Ippan Kokudō - Kantō;TMlightsalmon;4;preview
Ignored comment in systems.csv: #jpnhky;JPN;Japan Ippan Kokudō - Kyūshū;TMlightsalmon;4;preview
Ignored comment in systems.csv: #jpnhsh;JPN;Japan Ippan Kokudō - Shikoku;TMlightsalmon;4;preview
Ignored comment in systems.csv: #Devel Systems
Ignored comment in systems.csv: #afrcu;AFR;UEMOA Community Roads;TMlightsalmon;3;devel
Ignored comment in systems.csv: #agoen;AGO;Angola Estrada Nacional;TMgreen;3;devel
Ignored comment in systems.csv: #brabr;BRA;Brazil Rodovias Federais;TMgreen;4;devel
Ignored comment in systems.csv: #cuba;CUB;Cuba Autopista;TMblue;1;devel
Ignored comment in systems.csv: #ecue;ECU;Ecuador Primerias Red Vial Estatal;TMgreen;4;devel
Ignored comment in systems.csv: #fraaram38;FRA;Grenoble-Alpes Métropole Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #fraaram69;FRA;Lyon Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #frabrem29;FRA;Brest Métropole Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #frabrem35;FRA;Rennes Métropole Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #fracvlm37;FRA;Tours Métropole Val de Loire Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #fracvlm45;FRA;Orléans Métropole Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #fragesm57;FRA;Metz Métropole Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #franorm76;FRA;Métropole Rouen Normandie Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #franaqm33;FRA;Bordeaux Métropole Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #frapacm83;FRA;Toulon Provence Méditerranée Routes Métropolitaines;TMyellow;5;devel
Ignored comment in systems.csv: #idnah;IDN;Indonesia Asian Highways (split regions);TMred;2;devel
Ignored comment in systems.csv: #idnjwt;IDN;Java Jalan Tol;TMblue;1;devel
Ignored comment in systems.csv: #idnjwt;IDN;Java Ruta Nacional;TMlightsalmon;3;devel
Ignored comment in systems.csv: #idnkat;IDN;Kalimantan Jalan Tol;TMblue;1;devel
Ignored comment in systems.csv: #idnkat;IDN;Kalimantan Ruta Nacional;TMlightsalmon;3;devel
Ignored comment in systems.csv: #idnnut;IDN;Nusa Tenggara Jalan Tol;TMblue;1;devel
Ignored comment in systems.csv: #idnnun;IDN;Nusa Tenggara Ruta Nacional;TMlightsalmon;3;devel
Ignored comment in systems.csv: #idnppn;IDN;(West) Papua Ruta Nacional;TMlightsalmon;3;devel
Ignored comment in systems.csv: #idnslt;IDN;Sulawesi Jalan Tol;TMblue;1;devel
Ignored comment in systems.csv: #idnslt;IDN;Sulawesi Ruta Nacional;TMlightsalmon;3;devel
Ignored comment in systems.csv: #idnsmt;IDN;Sumatra Jalan Tol;TMblue;1;devel
Ignored comment in systems.csv: #idnsmt;IDN;Sumatra Ruta Nacional;TMlightsalmon;3;devel
Ignored comment in systems.csv: #irqf;IRQ;Iraq Freeways;TMblue;1;devel
Ignored comment in systems.csv: #jamb;JAM;Jamaica B Roads;TMyellow;5;devel
Ignored comment in systems.csv: #mexdn;MEX;Mexico Federal Expressways (new);TMblue;1;devel
Ignored comment in systems.csv: #mexedn;MEX;Mexico State Expressways (new);TMteal;3;devel
Ignored comment in systems.csv: #ukrn;UKR;Ukraine Nacional'ni Avtomobil'ni Dorohy;TMlightsalmon;4;devel
Ignored comment in systems.csv: #ukrr;UKR;Ukraine Rehional'na Avtomobil'na Doroha;TMyellow;5;devel
Ignored comment in systems.csv: #usatxf;USA;Texas Farm to Market Roads 1-499;TMyellow;5;devel
Ignored comment in systems.csv: #usatxf2;USA;Texas Farm to Market Roads 500-999;TMyellow;5;devel
Ignored comment in systems.csv: #usatxf3;USA;Texas Farm to Market Roads 1000-1499;TMyellow;5;devel
Ignored comment in systems.csv: #usatxf4;USA;Texas Farm to Market Roads 1500-1999;TMyellow;5;devel
Ignored comment in systems.csv: #usatxf5;USA;Texas Farm to Market Roads 2000-2499;TMyellow;5;devel
Ignored comment in systems.csv: #usatxf6;USA;Texas Farm to Market Roads 2500-2999;TMyellow;5;devel
Ignored comment in systems.csv: #usatxf7;USA;Texas Farm to Market Roads 3000-3499;TMyellow;5;devel
Ignored comment in systems.csv: #usatxf8;USA;Texas Farm to Market Roads 3500-4000;TMyellow;5;devel
Ignored comment in systems.csv: #usatxr;USA;Texas Ranch to Market Roads;TMyellow;5;devel`

**Comment by yakra** [comment]
* I thought about the "Ignored comment" notifications being a bit of a "buffer" separating the list of systems for *Reading systems list* and the same list of systems *Reading waypoints for all routes*, but somehow didn't think of removing it entirely! :rofl:
One thing I considered was slimming it down, e.g. `Ignored 54 comment(s) in systems.csv: eure2 eursf2 itaa2 itass2`but that **1,** would still look too much like the text before and after, and **2,** wouldn't play as nice with comments like `#Preview Systems` and `#Devel Systems`.
You're right, it's a long list, and we don't really need it. Comments are comments, and are meant to be ignored. :grin:
  * [ ] At the very least, let's get rid of it for datacheck.
  * [ ] Speculating here -- this may have helped make sure we were on the right track [when TM was barely 3 months old](https://github.com/TravelMapping/DataProcessing/commit/9ad76226b20072d31d5363bdbfe32ff60d064aca). Since then the project has matured and stabilized, and this has arguably outlived its usefulness. @jteresco, would you say this is meaningful for a standard site update? Keep it? Scrap it?
* [ ] The idea of having one big list of systems right smack up against another list of systems in the output makes me rethink the *Reading systems list* output. Keeping the `systemname` around for debug purposes isn't so important. If I need to do debugging, I'll be getting into the code anyway, and can temporarily add them back in then. Most likely, along with _other_ debug output too.
I could comment out part of this line 
https://github.com/TravelMapping/DataProcessing/blob/76589583c4da970b867655e8ca70bb73999201b4/siteupdate/cplusplus/classes/HighwaySystem/HighwaySystem.cpp#L63
 
  like so
  ```c++
  std::cout /*<< systemname*/ << '.' << std::flush;
  ```
  to leave us with just progress dots, or comment it _all_ out
  ```c++
  //std::cout << systemname << '.' << std::flush; 
  ```
  to leave progress indication out entirely. *Reading systems list* takes 0.4 s on noreaster, lab2 & BiggaTomato. 0.5 s on my slowest machine, lab3. [Future changes](https://github.com/yakra/DataProcessing/issues/230) may make it faster.

---

Something I meant to add to my last post, but forgot and hit `Comment` too early...

> [Highlight success message by blank lines](https://forum.travelmapping.net/index.php?topic=5359.msg30334#msg30334)

Another thought I had when first reading  the forum post ("more highlighted") was to output some escape codes to change the text color to green. This is not without its complications though...
* **Problem:** Having the escape code in siteupdate.log would be ugly in `less` or a web browser, and may complicate even opening the file at all in some other text viewers/editors.
* **Solution:** Write the color codes to `stderr` instead of `stdout`, to keep them from getting captured by `tee`.
I just tested `echo -en '\e[1m' 1>&2` in bash, and it works.
* **Problem:** The `2>&1` in siteupdate.sh.  This made sense for Python; if it crashes, it gives a stack trace, which is useful for debugging. C++ OTOH will almost never write to `stderr`. If it crashes, it just crashes, with no explanation of what happened. Except for really rare cases like unhandled exceptions, which, if I'm writing the code properly, shouldn't happen. :grin: We *could* remove it, but then again, siteupdate.sh still does have the `--use-python` option...
* **Potential solutions:**
  * Have the `2>&1` be a Python-only flag. But OTOH, if siteupdate.py is still being maintained alongside the C++ flavor for the time being, that arguably should get the colored text too. So maybe not such a good idea.
  * Decide we don't want `2>&1` at all. If there's a crash, anything we need to see should be right there in bash; probably not much point in having it in siteupdate.log?
* ...Or if this is all too much, maybe just add the 2 blank lines & leave it at that?

**Comment by michihdeu** [comment]
>[Highlight success message by blank lines](https://forum.travelmapping.net/index.php?topic=5359.msg30334#msg30334)

I'm in favor of keeping it as simple as possible.

**Comment by yakra** [comment]
@jteresco, I'm planning on eliminating the ["ignored systems" output](https://github.com/TravelMapping/DataProcessing/issues/574#issuecomment-1408941738) for `siteupdate --errorcheck` soon. Any thoughts on keeping/scrapping it for production site updates?

**Comment by jteresco** [comment]
> @jteresco, I'm planning on eliminating the ["ignored systems" output](https://github.com/TravelMapping/DataProcessing/issues/574#issuecomment-1408941738) for `siteupdate --errorcheck` soon. Any thoughts on keeping/scrapping it for production site updates?

I'm in favor of getting rid of it there too.

**Comment by yakra** [comment]
* [ ] When `creating .time files`, suppress output for either...
  * files already up to date.
  * all .time files altogether

**Comment by jteresco** [comment]
No output needed as far as I'm concerned.  Maybe just a single line "creating .time files"?

**Comment by yakra** [comment]
Works for me. Simple & clean code; simple & clean output.

**Comment by yakra** [comment]
**Done:**
* 7ebafca [Highlight success message by blank lines](https://github.com/TravelMapping/DataProcessing/issues/574#issue-1558353085)
* 89f079c [nix progress dots for read_wpt](https://github.com/TravelMapping/DataProcessing/issues/574#issue-1558353085)
* d7f64b9 [only print `traveler_name` sans `.list` extension](https://github.com/TravelMapping/DataProcessing/issues/574#issuecomment-1408924231)
* c13439f [silently ignore systems.csv comments](https://github.com/TravelMapping/DataProcessing/issues/574#issuecomment-1408941738)
* d2d6f61 system names -> [progress](https://github.com/TravelMapping/DataProcessing/issues/574#issuecomment-1408924231) [dots](https://github.com/TravelMapping/DataProcessing/issues/574#issuecomment-1411317421) for systems.csv

**Still needs attention, from the OP:**
- [Remove "skip lines"](https://forum.travelmapping.net/index.php?topic=5359.msg30338#msg30338)
  * [ ] `./datacheck.sh: SKIPPING file copies and DB update`
  Easy, `exit 0` before this happens.
  * [ ] `./datacheck.sh: SKIPPING nmpbyregion (no ../nmpfilter/nmpbyregion executable)`
  Question: do we *want* to produce nmpbyregion files as part of datacheck?
    * Is it something useful, something data managers would look at & reference?
    * If running on a remote machine such as noreaster, one has to download the files to their local machine to upload to HDX.
    * FWIW, my [dashboard script](https://forum.travelmapping.net/index.php?topic=4553) only prints lines from nearmisspoints.log, for easy pasting into nmpfps.log as needed.
    * If we decide we do want them, this raises a few more minor issues, easy to solve.

**Comment by michihdeu** [comment]
> Question: do we want to produce nmpbyregion files as part of datacheck? 

No strong feeling. I love the option but... I never did so far.
