### ISSUE TITLE
Stop site update after errors

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#575]
With the new siteupdate still in the commonupdate branch:

If C++ siteupdate fails, it still writes some of the .sql file, and then siteupdate.sh tries to use it.

**Comment by yakra** [comment]
Weird. Don't know why siteupdate.sh would still be running in order to try to use it, if there's the `|| exit 1` if siteupdate fails.
https://github.com/TravelMapping/DataProcessing/blob/0af3140135b8b12ee160444f44f68e44a0cc3a11/siteupdate/siteupdate.sh#L306
Did siteupdate abort due to `ErrorList` errors, or did it crash?
What were your HighwayData, UserData & DataProcessing commits? `git show -s`

**Comment by michihdeu** [comment]
I guess that [this](https://github.com/TravelMapping/HighwayData/commit/59afa75034635820caaa88dec2dd0aa032e6deb7) caused the issue.

**Comment by yakra** [comment]
@michihdeu thanks for the commit info. I'll use [the parent commit](https://github.com/TravelMapping/HighwayData/commit/f82ae4c18f29b68d33840dbbf53258b64ba591b4) for testing purposes.

@jteresco I'm not sure I'll get the same behavior under Linux as under FreeBSD. Back when I opened #383 it had been a while since I'd observed what happened and how. Time to refresh my memory I guess. Test out a few different command lines under CentOS, Ubuntu & FreeBSD, Python & C++ flavors...

If all else fails, we can always `tail -n 1 siteupdate.log | grep -c 'Total run time:'`...

**Comment by yakra** [comment]
~Maybe BSD `tee` returns the same exit code as whatever's piped to it, and Linux `tee` just returns 0?~

* `./siteupdate -e -t 4 -d .//TravelMapping -l .//logs -c .//stats -g .//graphs -u $HOME/tm/UserData/list_files -w $HOME/tm/HighwayData | tee siteupdate.log || echo FAIL FAIL FAIL` does not actually echo FAIL FAIL FAIL. Observed under Ubuntu & CentOS, and a bit surprisingly, also on Noreaster.
* `(./siteupdate -e -t 4 -d .//TravelMapping -l .//logs -c .//stats -g .//graphs -u $HOME/tm/UserData/list_files -w $HOME/tm/HighwayData || echo FAIL FAIL FAIL) | tee siteupdate.log` behaves as expected. Hm. I thought I had tried parentheses that time years ago? Good to see.
