### ISSUE TITLE
C++ siteupdate: Use of sprintf, deprecated on MacOS/XCode

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#585]
When compiling on MacOS, the C++ site update code generates pages of warnings:

<pre>siteupdate.cpp:527:4: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                        sprintf(fstr, ": %.2f mi", cr->mileage);
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
</pre>

I'm ok leaving it or replacing our `sprintf` calls with `snprintf` calls.  A little of what I saw when searching around on this is that there are also some more C++-specific ways to achieve the same result.

Compiler version:

<pre>
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
</pre>

**Comment by yakra** [comment]
[fprintf](https://cplusplus.com/reference/cstdio/fprintf/) may be able to get rid of most or even all of the `sprintf` calls altogether.

The downside is that it uses C's [FILE](https://cplusplus.com/reference/cstdio/FILE/) rather than C++'s [std::ofstream](https://cplusplus.com/reference/fstream/ofstream/), so it'd involve a little reinvention  of the wheel.

**Comment by yakra** [comment]
## Great news:
sprintf is a performance killer. Yes, this *is* great news.
Getting rid of it inner loops is **the Magic Bullet for fixing poor FreeBSD performance. *Including graph generation.***

Most uses format a string and immediately plop it into a file.
Here, we can use `ofstream.precision`, occasionally `setf` and `unsetf`, and more traditional `<<` operators.
* **graph generation**
  This finally opens the floodgates & allows graph generation to scale to a higher number of threads on FreeBSD.
  As of 32829211cd8f93bb26a76d8ac339e4c454168a55 ([yakra#251](https://github.com/yakra/DataProcessing/issues/251)), lab2 (CentOS) was just shy of breaking the 3-second barrier.
  With this, it averages 1.0088 s, even managing 0.9985 on one run.
  *FreeBSD even outperforms both CentOS and Ubuntu now.*
  Caveats:
  * bsdlab has different RAM chips from lab3 & lab4, which may have different timings. I doubt this is *the* contributing factor, but worth noting. Heck, it could even be that bsdlab has *slower* timings.
  * Different clang versions are used; 9.0.1, 6.0.0 and 11.0.1 for lab3, lab4 and bsdlab respectively.)
* **sqlfile1**
  sprintf is removed from `sqlfile1` locally. I've done "after" benchmarks, but not "before" yet.
  As sqlfile1 is run in the background during graph generation, it made sense to convert this over too before benchmarking graphs.
  There was already no sprintf in sqlfile2.
* **userlogs**
  Another task that scaled poorly under FreeBSD.
  Here are links to charts of how [the](https://github.com/TravelMapping/DataProcessing/pull/607#issuecomment-1712928313) [last](https://github.com/TravelMapping/DataProcessing/pull/592#issuecomment-1627785857) [three](https://github.com/TravelMapping/DataProcessing/pull/526) performance improvements played out.
  This was *slightly* less straightworward: The `format_clinched_mi` function, which fomatted and returned a `char*` is gone, replaced by a lambda that captures `std::ofstream log`. Several of the long series of `ofstream` insertions had to be broken up into 2 or 3 separate commands.

### ToDo:
* **near-miss points**
  Similar to userlogs in that there's also [Waypint::str()](https://github.com/TravelMapping/DataProcessing/blob/fd96ac64ba2eff23600e86df8dcc84e94cb0a916/siteupdate/cplusplus/classes/Waypoint/Waypoint.cpp#L76-L82) to contend with, also a good candidate to be replaced by a lambda. Shouldn't be too complicated.
* **routedatastats.log**
  should be pretty straightforward.
* **stats CSVs**
  likewise. There's a multithreaded stats CSV option, disabled by default because it performed so poorly, even on Linux. Getting rid of sprintf may change that.

The remaining uses do use the results for string manipulation, not just writing to a file. These cases are infrequent enough that I can just accept using `snprintf` instead; any performance will be negligible.
* Flagging a handful of datachecks:
   LONG_SEGMENT, SHARP_ANGLE, OUT_OF_BOUNDS, VISIBLE_DISTANCE, DUPLICATE_COORDS,
* ElapsedTime::et()
* GraphListEntry::tag()
* And finally, WaypointQuadtree::str(). I think there are no calls to this at all other than some commented-out debug stuff.

---

I'm going to hold off on a pull request for this for a wee bit.
yakra#251 is finally ready to go, so I want to gather up the stats, make some benchmark charts, type out the pull request text and get that in. If not later today, Tuesday.
LOL, after more than a month of perfecting that, this comes along, takes a few minutes to change a couple dozen lines of code, and has a far bigger impact! :grin:
