### ISSUE TITLE
Site update parameter to use different NMP thresholds

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#590]
Could add a command-line parameter to the site update programs to allow different NMP thresholds.

https://forum.travelmapping.net/index.php?topic=5314.msg31206#msg31206

It would be unlikely we would change these for production site update runs, but runs could be made by individuals to either use a smaller threshold to limit false positives or a larger threshold to search for unaligned intersection points that are farther away than our default.

**Comment by yakra** [comment]
Even [if siteupdate.py is deprecated](https://github.com/TravelMapping/DataProcessing/issues/595#issuecomment-1659458104) and this option won't make it into the Python version, I think it still makes sense to be consistent and have both a short & long switch for each argument.
* `-N` seems an obvious choice for the short one.
* What about the long one? `--nmp-threshold`? `--nmp-thresh`?

**Comment by michihdeu** [comment]
@yakra Sorry, I didn't realize that your [response on the forum](https://forum.travelmapping.net/index.php?topic=5314.msg32786#msg32786) was to my request. I think that `LOOKS INTENTIONAL` would mean coords being off by exactly 0.000001°. However, I meant coords being of by < 0.01mi.

I manually checked more than 10,000 NMP pairs in France over the past months. I did it region by region and either fixed them or marked FP. I was surprised that there were so many true positives. I always made a second (even more dull) run for each region to catch errors I made during the first run, and there where quite some with very small offset.
So, my French regions are done now - except of FRA-COR being maintained by Si. There are 11,285 FPs. However, I fear that there are some NMPs with very small offset I've marked FP by accident. **Is it possible to make a one-time run with very small NMP threshold for me? All coords being of by ~ 0.01mi?** I would download that file and upload to HDX. The next run can be as usual again. It's fine when it is just tm-master.nmp.

@yakra  or @jteresco is it possible?

**Comment by jteresco** [comment]
I am sure I can modify and compile up a temporary version of siteupdate (or just add the parameter while I'm doing it) and run with whatever threshold you want.  In the runs now, it's set at a tolerance to find points within 0.0005 degrees latitude and longitude.

**Comment by michihdeu** [comment]
thanks @jteresco I think that 0.0001° would be great 😄

**Comment by jteresco** [comment]
@michihdeu I ran with the 0.0001 threshold but not on the production server.  You just want tm-master.nmp?

**Comment by michihdeu** [comment]
> @michihdeu I ran with the 0.0001 threshold but not on the production server. You just want tm-master.nmp?

yep. tm-master.nmp is enough. Please let me know where I can download it. Thanks 😄

**Comment by jteresco** [comment]
https://www.teresco.org/temp/tm-master.nmp

**Comment by michihdeu** [comment]
Thanks! There was exactly ONE NMP in FRA-IDF which was marked FP by accident 😃

**Comment by yakra** [comment]
#612
