### ISSUE TITLE
Datacheck outputs error when executing for railway data

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#603]
Data check works fine but the log always outputs this:
`segment name mismatch in HGEdge collapse constructor: edge1 named C,N,U edge2 named C,N,CVer,U`
https://forum.travelmapping.net/index.php?topic=5644.msg31795#msg31795

**Comment by yakra** [comment]
Just saw this issue today. I'll look into it.

**Comment by yakra** [comment]
```sh
grep TERMINUS _1af2/logs/datacheck.log 
cze.s05jih;+X956404;;;HIDDEN_TERMINUS;
cze.s06jih;+X956404;;;HIDDEN_TERMINUS;
cze.s09jih;+X956404;;;HIDDEN_TERMINUS;
deunw.s11;+X290753;;;HIDDEN_TERMINUS;
deunw.u76;+X827836;;;HIDDEN_TERMINUS;
italom.m01;+CinBet;;;HIDDEN_TERMINUS;
italom.m04;+SanCri;;;HIDDEN_TERMINUS;
```
There's the problem, right in the first 3.
I assume a similar problem was fixed for the routes in the OP.

**Comment by yakra** [comment]
>  I assume a similar problem was fixed for the routes in the OP.

Weird. AFAICT, this would have to mean a HIDDEN_TERMINUS on `CVer`.
The only matching route I see is:
```sh
yakra@BiggaTomato:~/tm/RailwayData/data/_systems$ grep ';C.*Ver;' `ls *.csv | grep -v _`
frarer.csv:frarer;FRA-IDF;C;;Ver;Versailles-Chateau-Rive-Gauche - Versailles-Chantiers;fraidf.rercver;
```
Going back thru `fraidf.rercver.wpt`'s [history](https://github.com/TravelMapping/RailwayData/commits/master/data/FRA-IDF/frarer/fraidf.rercver.wpt) as far as [ced32f0](https://github.com/TravelMapping/RailwayData/commit/ced32f0d581baa7f40f66b79f95ddf0ad27d2329), I don't see such an error.
Was there another `CVer` that was renamed?

**Comment by yakra** [comment]
OK wait, I think I get it...

For the three CZE routes here, wptedit only reports a LABEL_TOO_LONG error.
Problem is, if a label is too long to fit in the DB, siteupdate tosses that point out of the system entirely. It doesn't even exist anymore.
Meaning, if the first or last waypoint's label is too long, the route is effectively truncated. The new "terminus" is the 2nd or 2nd-last (as the case may be) point in the route -- `+X956404` in the case of the 3 CZE routes. *(LOL that "404" bit is especially fitting! :rofl:)*

Taking another look at the 29 July commit for fraidf.rercver.wpt, I see a terminus of `VersaillesChateauRiveGauche` -- too long by one letter.
On 21 Aug, @si404 changed it to `VerChaRiveGau`, short enough to fit in the DB. No more LABEL_TOO_LONG, the real terminus is the real terminus now, no more HIDDEN_TERMINUS, and no problem with the HGEdge collapse constructor.

**Comment by michihdeu** [comment]
Oh, thanks for going down the rabbit hole @yakra  I just didn't expect that `C,N,U` are route names!
I just why the Czech routes were not output back then. The wpt files, csv files and systems.csv have not been changed since July 30. Thus, they should had been output too.

Anyway, thanks for figuring this out. I don't know if this kind of error REPORT in the log is best.
It's fine that data check is _successful_ since a data error is output. I don't see any need for the log output.

**Comment by yakra** [comment]
> I don't know if this kind of error REPORT in the log is best.

This check was more important in the past. I believe it dates back to when @jteresco  was first getting collapsed graph generation (hence adding the `graph generation` tag to this issue) off the ground, and is more of a notice of *"Hey, there's something unexpected going on in the `HGEdge` (AKA HighwayGraph Edge) collapse constructor; you may wanna look into that"* rather than necessarily an indication of a route data issue.

That said though, I think this report has outlived its usefulness.
As noted [here](https://github.com/TravelMapping/DataProcessing/issues/91#issuecomment-1526812024), sorting Waypoint colocation lists combined with bugfixes to concurrency detection have resulted in deterministic concurrency lists, eliminating cases like in the OP of #91.
These days, this error only occurs when there are HIDDEN_TERMINUS errors in the route data. And as @michihdeu notes,
> It's fine that data check is _successful_ since a data error is output. I don't see any need for the log output.

These data errors are logged in datacheck.log and on datacheck.php. Which should be sufficient for getting the underlying errors fixed.
I've been considering [nixing `HGEdge::segment_name`](https://github.com/TravelMapping/DataProcessing/issues/589) in order to improve graph generation efficiency. No longer having this datum to compare would mean no more error report in siteupdate.log. :)

**Comment by yakra** [comment]
> I just why the Czech routes were not output back then.

I just did a `git checkout f52bb70` in RailwayData and ran siteupdate built from 1af229da874b9a5b6fe3c6568e1fdc6fada07d34.
>[1.0] Creating edges.............................................................!
>[1.1] Compressing collapsed edges..ERROR: segment name mismatch in HGEdge collapse constructor: edge1 named S5Jih,S6Jih edge2 named S9Jih
>
>.ERROR: segment name mismatch in HGEdge collapse constructor: edge1 named C,N,U edge2 named C,N,CVer,U
>
>.!
>[1.1] Writing graph waypoint simplification log.

All I can suggest here is that maybe you didn't notice it being on the same line as `Compressing collapsed edges..`, not on its own line surrounded by whitespace.

**Comment by yakra** [comment]
Let's consider the scope of this issue to be the cases in the 1st 2 posts & the forum link in the OP.
Closing this issue for housekeeping purposes, as there are already several issues dealing with segment name mismatch errors more generally: #91 #178 #360 #589
