### ISSUE TITLE
Options to generate only a subset of graphs of interest

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#78]
This is mainly in relation to the highway data check mode of the site update program.  If only a subset of the data is used, the graph processing will likely crash.  Do we want to be able to generate only a small subset of graphs?

**Comment by jteresco** [comment]
The thought that comes to mind for both this and #79, though, is how much time is worth putting in to get code to generate only a subset of graphs to save the few minutes it takes to generate all of them.  So these are likely to be low priority.

**Comment by michihdeu** [comment]
If I got it right, this is a bug report because graph generation crashes if the number of systems/regions is too low and #79 is a feature to detect and select the required graphs?

I agree that it's not high priority because Jim's server is a little bit faster than yakra's offline version. Assuming 65% it would about 20 minutes in total.

**Comment by yakra** [comment]
I just tested siteupdate using only two systems, one active & one preview. It ran to completion; graph generation was fine. 2c9d199da1d34e77c53543de3d1ab070120859a8 seems to have done the trick.

That, and graph generation has become an order of magnitude faster since this issue was opened.

Can this be closed?

**Comment by jteresco** [comment]
Deeming no longer a significant issue.  @yakra or @michihdeu or others, feel free to reopen if you disagree.
