### ISSUE TITLE
Graph generation: new "segment name mismatch" errors

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#91]
Recent highway data changes (possibly including? https://github.com/TravelMapping/HighwayData/commit/de8de02018340f0726b707b900254c5d914fe2c7 ) have resulted in a few new errors being reported during graph generation:

<pre>
ERROR: segment name mismatch in HighwayGraphCollapsedEdgeInfo: edge1 named E008,AH66,A385 edge2 named AH66,A385,E008

ERROR: segment name mismatch in HighwayGraphCollapsedEdgeInfo: edge1 named AH66,A385,E008 edge2 named E008,AH66,A385

ERROR: segment name mismatch in HighwayGraphCollapsedEdgeInfo: edge1 named AH7,A384,E123 edge2 named E123,AH7,A384
</pre>

Opening this issue as a reminder to investigate.

**Comment by yakra** [comment]
Same route names, different order... Do route names get added to edge names, on a first-come-first-serve basis, with no sorting performed?
https://github.com/TravelMapping/DataProcessing/blob/674d671789b0ab23c11786dafeb09173a182c282/siteupdate/python-teresco/siteupdate.py#L594-L606
https://github.com/TravelMapping/DataProcessing/blob/674d671789b0ab23c11786dafeb09173a182c282/siteupdate/python-teresco/siteupdate.py#L1515-L1530

**Comment by yakra** [comment]
Test with HighwayData @ a46d6d9b7ca2f2f452f7e3ebe7123e109e51ced2

**Comment by yakra** [comment]
related: #360

**Comment by jteresco** [comment]
Still relevant, @yakra?

**Comment by yakra** [comment]
I'd like to check out the commit listed above and take a closer look at things, test some stuff out, but it's a low priority.

**Comment by yakra** [comment]
The [first](https://github.com/TravelMapping/DataProcessing/issues/135) of [two](https://github.com/TravelMapping/DataProcessing/issues/449) bugfixes for concurrency detection, along with cdea81e3e67ae0347e5f7e37b882e31c1d074d35 a few months after the OP, order colocation lists deterministically, and we should no longer have problems like those in the OP.

OTOH (and I'm a little surprised I don't see this mentioned more directly upthread), there was that one time an active route in Oregon had a HIDDEN_TERMINUS error for a few months.
That may not have actually triggered this error; ISTR that the hidden point on the one route may have been visible on the other, making the vertex visible overall, thus no edge compression happened there.
(Hopefully the commit [above](https://github.com/TravelMapping/DataProcessing/issues/91#issuecomment-631214767) is the right one to check this out?)

However, if *all* colocated points are hidden, we'll definitely get the error.

https://github.com/TravelMapping/DataProcessing/blob/80f27243bf26579c53c6c7a215a5aeb22347317a/siteupdate/cplusplus/classes/GraphGeneration/HGEdge.cpp#L56-L57

For regular concurrencies not involving a HIDDEN_TERMINUS, there'll be >2 edges, meaning we won't be compressing here. Thus it's only HIDDEN_TERMINUS cases we need to worry about.

Posting here because this is related to an `HGEdge` RAM/efficiency idea that'd involve accounting for these errors before we get to the `HGEdge` construction stage. More to come soon in a new issue.

**Comment by yakra** [comment]
One more post here to debunk a comment I made [above](https://github.com/TravelMapping/DataProcessing/issues/91#issuecomment-1526812024):

> For ~regular~ concurrencies not involving a HIDDEN_TERMINUS, there'll be >2 edges, meaning we won't be compressing here. Thus it's only HIDDEN_TERMINUS cases we need to worry about.

The *(concurrent sans HIDDEN_TERMINUS) -> (>2 edges)* statement is false.
To disprove, let's find a counterexample where the premise is true & conclusion is false.
Instead of a hidden terminus, consider a hidden "U-turn" (not unlike `PA US19TrkPit I-376(69A)`) point, where both the part in & path out on a given route collapse into a single edge. Hidden end of an edge, but not a hidden *terminus*.
Real-world example: RailwayData @ eeea42f,
OR/usapsc/or.blp.wpt @ +DIV_Nor
OR/usapsc/or.nsln.wpt @ +DIV_Nor

This means any other conclusions I made based on this may not be true, and need a rethink.
I'll look thru my other posts & maybe link back here...
