### ISSUE TITLE
Better error handling when an I/O exception occurs

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#96]
The site update process is not good at recovering/exiting gracefully from an I/O exception.  In particular, siteupdate.py will crash but localupdate.sh will not notice (and will try a DB update) if an encoding error occurs.  For example, the encoding problems in updates.csv that were introduced in https://github.com/TravelMapping/HighwayData/pull/2143 crashed siteupdate.py.

**Comment by michihdeu** [comment]
Thanks. So it would only be logged once errors are caught like Jim has suggested.

**Comment by jteresco** [comment]
Seems this hasn't come up for almost 4 years.  No longer relevant?  Maybe something that can be addressed better during an attempt at #551?

**Comment by michihdeu** [comment]
I didn't face the issue for a very long time now. I'm fine with closing.

**Comment by yakra** [comment]
@jteresco [wrote](https://github.com/TravelMapping/DataProcessing/issues/96#issuecomment-447660281):
> A similar issue occurs with a ValueError exception when a string that should be convertible to a number is not. See https://github.com/TravelMapping/HighwayData/pull/2421 for a place where this showed up. These should be handled more gracefully and with a meaningful log/error message.

This has been handled by MALFORMED_LAT & MALFORMED_LON for some time now.
Don't know if this issue was opened before `ErrorList` was implemented, but that  handles other concerns (e.g. file not found) well. I rarely see errors; it's been a long time.
I think we're fine closing this, and any specific new issues re data encoding, datachecks, ErrorList checks etc. can be opened as needed.

**Comment by jteresco** [comment]
Good enough for me.  Closing.
